spring.profiles.include=local
spring.application.name=tfmBack
spring.data.mongodb.uri=mongodb://localhost:27017/portfolio
spring.data.mongodb.database=portfolio
spring.mongodb.uri=mongodb://localhost:27017/portfolio
spring.mongodb.database=portfolio
server.port=8080

# Resend Configuration
resend.api-key=${RESEND_API_KEY}
resend.send-to=juliaelguetaserra@gmail.com
# Use onboarding@resend.dev if you haven't verified a domain yet
resend.send-from=My App Contact <onboarding@resend.dev>

# Security Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=70000